- hosts: webservers
  become: yes
  tasks:
  - name: "Install Nginx"
    yum:
      name: ['nginx']
      state: latest
  - name: "Enable Nginx"
    service:
      name: nginx
      enabled: yes
  - name: "Start nginx"
    service:
      name: nginx
      state: started
  - name: "Create WWW Directory"
    file:
      path: /var/www/html
      state: directory
      mode: '0775'
      owner: "nginx"
      group: "nginx"
  - name: "Disable Selinux"
    shell: setenforce 0